### ISSUE TITLE
[BUG] version_checker_leaf.py pcie_retimer failed, manifest/pcie_retimer.yml not found.

### ISSUE THREAD

**Issue by ZhenshengLee** [ZhenshengLee/nv_driveworks_demo#21]
**Required Info:**
- Software Version
[ ] DRIVE OS 6.0.6
- Target OS
[ ] Linux
- SDK Manager Version
[ ] 1.9.2.10884
- Host Machine Version
[ ] native Ubuntu Linux 20.04 Host installed with DRIVE OS DOCKER Containers

**Describe the bug**

version-checker pcie_retimer failed, '/etc/nvidia/version_checker/manifest/pcie_retimer.yml'

**To Reproduce**

```sh
nvidia@tegra-ubuntu:~/zhensheng/orin_ws/nv_driveworks_demo/target$ sudo version_checker_root.py -i /etc/nvidia/version_checker/manifest/version_data_root.yml
===============================
ROOT VERSION CHECKER
===============================
Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/rootfs_debians.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545

Start checking version of "Filesystem debian packages".
*** Rootfs Manifest could not be read. ***
Finished checking version of "Filesystem debian packages".

Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/ethernet_firmware_1.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545

Start checking version of "Oak Eth Switch SPI Config ROM SMI_ADDRESS=8".
Invoking  /bin/bash -c '/lib/firmware/marvell_ethernet/common/ota/linux/nvidia/update-firmware.sh --printversion | grep "Full firmware version at SMI_ADDRESS=8:"| cut -d" " -f6'

*** Version matches on firmware "Oak Eth Switch SPI Config ROM SMI_ADDRESS=8", expected and found 00.07.1186.01 ***
Finished checking version of "Oak Eth Switch SPI Config ROM SMI_ADDRESS=8".

Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/ethernet_firmware_2.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545

Start checking version of "Spruce Eth Switch SPI Config ROM SMI_ADDRESS=4".
Invoking  /bin/bash -c '/lib/firmware/marvell_ethernet/common/ota/linux/nvidia/update-firmware.sh --printversion | grep "Full firmware version at SMI_ADDRESS=4:"| cut -d" " -f6'

*** Version matches on firmware "Spruce Eth Switch SPI Config ROM SMI_ADDRESS=4", expected and found 00.07.1186.01 ***
Finished checking version of "Spruce Eth Switch SPI Config ROM SMI_ADDRESS=4".

Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/ethernet_firmware_3.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545


Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/ethernet_phy_firmware_1.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545


Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/ethernet_phy_firmware_2.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545


Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/ethernet_cx6-dx_firmware.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545

Start checking version of "Mellanox CX-DX6 ethernet NIC on P4024".
*** No compatible board found for firmware "Mellanox CX-DX6 ethernet NIC on P4024". ***
*** Skipping version check for firmware "Mellanox CX-DX6 ethernet NIC on P4024". ***
Finished checking version of "Mellanox CX-DX6 ethernet NIC on P4024".

Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/aurix_firmware_1.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545

Start checking version of "AURIX Safety MCU AFW".
Invoking  /bin/bash -c 'common_if_testapp -get_fw_version | grep "Flashed AURIX fw version" | cut -d" " -f5'

*** Version matches on firmware "AURIX Safety MCU AFW", expected and found 5.07.06.00 ***
Finished checking version of "AURIX Safety MCU AFW".

Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/aurix_firmware_2.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545

Start checking version of "AURIX Safety MCU UPDATE FW".
Invoking  /bin/bash -c 'common_if_testapp -get_update_fw_version | grep "Flashed UPDATE fw version" | cut -d" " -f5'

*** Version matches on firmware "AURIX Safety MCU UPDATE FW", expected and found 1.48.01.00 ***
Finished checking version of "AURIX Safety MCU UPDATE FW".

Invoking python3 /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/pcie_retimer.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545


Root version checker returned -1.
```

```sh
nvidia@tegra-ubuntu:~/zhensheng/orin_ws/nv_driveworks_demo/target$ sudo /usr/sbin/version_checker_leaf.py -i /etc/nvidia/version_checker/manifest/pcie_retimer.yml -b 940-63710-0010-000 -s 6.0.6.0-32441545
Traceback (most recent call last):
  File "/usr/sbin/version_checker_leaf.py", line 248, in <module>
    leaf_version_checker = LeafVersionChecker(config_file=YAML_FILE,
  File "/usr/sbin/version_checker_leaf.py", line 56, in __init__
    yaml_data = self.read_config(config_file)
  File "/usr/sbin/version_checker_root.py", line 156, in read_config
    with open(yaml_file, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/nvidia/version_checker/manifest/pcie_retimer.yml'
```

**Expected behavior**

we can check the version of pcie_retimer.

**Actual behavior**

`FileNotFoundError: [Errno 2] No such file or directory: '/etc/nvidia/version_checker/manifest/pcie_retimer.yml'`

**Additional context**

the firmware is updated with the command and report no error.

```sh
sudo /usr/lib/firmware/astera_retimer/tools/eeprom /usr/lib/firmware/astera_retimer/firmware/pt4080l/1.25.x/nvidia_p3713_x4x4/nvidia_P3713_x4x4_X8-B2B_RETIMER-DYN_PRT_ORIENT-SRNS-CLK_IND-HOT_PLUG-GPIO_PERST_v1_25_9.ihx
```

**Comment by ZhenshengLee** [comment]
linked to https://forums.developer.nvidia.com/t/bug-version-checker-leaf-py-pcie-retimer-failed-manifest-pcie-retimer-yml-not-found/258284

**Comment by ZhenshengLee** [comment]
VickNV Moderator
July 20
We have solved this issue and the fix will be available in a future release. Thanks.
